Mission04_juandm/Models/GradeCalculatorModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_juandm.Models
{
    public class GradeCalculatorModel
    {
        [Required]
        public int Assignment { get; set; }
        public int GroupProject { get; set; }
        public int Quiz { get; set; }
        public int Midterm { get; set; }
        public int Final { get; set; }

        public int Intex { get; set; }

    }
}

Mission04_juandm/Controllers/BlahController.cs
using Microsoft.AspNetCore.Mvc;
using Mission04_juandm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission04_juandm.Controllers
{
    public class BlahController : Controller
    {
        public IActionResult Index()
        {
            
            return View();
        }

        [HttpGet]
        public IActionResult GradeCalculator()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GradeCalculator(GradeCalculatorModel model)
        {
            return View();
        }
    }
}

Mission04_juandm/Views/Blah/GradeCalculator.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model GradeCalculatorModel;

<h2>Grade Calculator!</h2>
<h3>Enter grades between 0-100 for each task, Good Luck!</h3>
<br />
<form method="POST">
    <label>Assignments:</label>
    <input id="Assignment" asp-for="Assignment" /><br /><br />

    <label>Group Projects:</label>
    <input id="GroupProject"  asp-for="GroupProject" /><br /><br />

    <label>Quizzes:</label>
    <input id="Quiz"  asp-for="Quiz" /><br /><br />

    <label>Midterm Exam:</label>
    <input id="Midterm"  asp-for="Midterm" /><br /><br />

    <label>Final Exam:</label>
    <input id="Final"  asp-for= "Final"/> <br /><br />

    <label>INTEX:</label>
    <input id="Intex"  asp-for= "Intex"/><br /><br /><br />
    <div style="text-align:center;">
        <input id="btnCalculate" type="submit" value="Calculate Grade for IS 413" />
    </div>

    <div asp-validation-summary="All"></div>
</form>

<br />
<br />

Mission04_juandm/Views/Blah/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Mission 04";
}

<h1> Welcome to my website, my name is Juan Diego but I go by JD!</h1>
<img src="img/JDphoto.jpg" />
<p>I don't have a picture of me doing what I like to do because I like to take pictures haha! I have a 1986 Canon film camera, and I go around and take cool pictures with it, click <a href="https://www.instagram.com/film.sniper/" target="_blank">here</a> to see some of them!</p>
<p>From this class, I hope to get some good experience/knowledge writing cool web apps. I am excited to learn C# because I have heard so many people use it! This will help me in my future jobs.</p>
<p>Speaking of jobs, here is my top 3 list of jobs I am the most interested in pursuing after graduating:</p>
<br />
<ol>
    <li>Start my own Business</li>
    <li>Technology Consulting</li>
    <li>Data Analytics</li>
</ol>

Mission04_juandm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.ico">
    <title>@ViewData["Title"]</title>
    <link href="lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/main.css" rel="stylesheet" />
</head>
<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index"> Home</a>
        <a asp-controller="Blah" asp-action="GradeCalculator"> Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <footer>
        <p>Copyright © 2023 JD Mestanza</p>
        <p>All rights reserved</p>
        <p>Follow me on IG:<a href="https://www.instagram.com/film.sniper/" target="_blank">film.sniper</a> </p>
    </footer>

    <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/js/GradeCalculator.js"></script>
</body>
</html>